/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ooad.uml.editor;

import javax.swing.*;

public class App {
    
    private void start() {
        JFrame frame = new JFrame("My OOAD UML Editor");
        //Add the ubiquitous "Hello World" label.
        JLabel label = new JLabel("Hello World");
        frame.getContentPane().add(label);
 
        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        App application = new App();
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                application.start();
            }
        });
    }
}
